name: Deploy Frontend

on:
  push:
    branches: [ main ]  # or your primary branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Guest_House_Portal/client
            git pull
            npm install
            npm run build
            sudo cp -r build/* /var/www/html/
            pm2 restart frontend || pm2 start --name frontend "npx serve -s /var/www/html -l 3000"